require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rake
  - ./lib/rubocop/cops/custom_validator_name.rb
  - ./lib/rubocop/cops/sexy_migration.rb
  - ./lib/rubocop/cops/variable_name.rb
  - ./lib/rubocop/cops/remove_status_ok.rb

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'lib/seeds/**/*'
    - '.idea/**/*'
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Custom/UsePrefixForCustomValidator:
  Include:
    - 'app/models/**/*'

Custom/UseSexyMigrationSyntax:
  Include:
    - 'db/migrate/*'

Custom/RemoveRedundantStatusOk:
  Include:
    - 'app/controllers/**/*'

Custom/VariableName:
  Enabled: true

Gemspec/DependencyVersion:
  Enabled: true

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Style/AccessorGrouping:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - spec/**/*

Style/IpAddresses:
  Exclude:

Style/SymbolProc:
  Exclude:
    - 'db/migrate/**/*'
    - 'config/**/*'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ExtraSpacing:
  Exclude:
    - db/migrate/*

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    associations:
      - belongs_to
      - has_one
      - has_many
      - has_and_belongs_to_many
    enums:
      - enum
    validations:
      - validates
      - validate
    callbacks:
      - before_validation
      - after_validation
      - before_save
      - around_save
      - after_save
      - before_create
      - around_create
      - after_create
      - before_update
      - around_update
      - after_update
      - before_destroy
      - around_destroy
      - after_destroy
      - after_commit
      - after_rollback
    scopes:
      - scope
    constants:
      - constant
    class_methods:
      - def self.method_name
    instance_methods:
      - def method_name
  ExpectedOrder:
    - module_inclusion
    - constants
    - associations
    - enums
    - validations
    - callbacks
    - scopes
    - class_methods
    - instance_methods

Layout/RedundantLineBreak:
  Enabled: false

Layout/TrailingWhitespace:
  AllowInHeredoc: false

Layout/ArgumentAlignment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/LineLength:
  Max: 140
  AllowedPatterns:
    - !ruby/regexp /\A +(it|describe|context|shared_examples|include_examples|it_behaves_like) ["']/

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Lint/EmptyFile:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'app/models/concerns/*.rb'
    - '**/*.gemspec'
    - 'config/routes.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15

Naming/InclusiveLanguage:
  Enabled: true
  CheckStrings: true
  FlaggedTerms:
    ' a offense':
      Suggestions:
        - an offense
    auto-correct:
      Suggestions:
        - autocorrect
    auto_correct:
      Suggestions:
        - autocorrect
    behaviour:
      Suggestions:
        - behavior
    offence:
      Suggestions:
        - offense
    relevancy:
      Suggestions:
        - relevance
    'rune stone':
      Suggestions:
        - runestone
    lycantrope:
      Suggestions:
        - lycanthrope

#RSpec:
#  Language:
#    Expectations:
#      - expect_autocorrect_options_for_autocorrect
#      - expect_autocorrect_options_for_autocorrect_all
#      - expect_autocorrect_options_for_fix_layout
#      - expect_correction
#      - expect_feature_loader
#      - expect_no_offenses
#      - expect_offense
#
#RSpec/FilePath:
#  Exclude:
#    - spec/rubocop/cop/internal_affairs/redundant_let_rubocop_config_new_spec.rb
#    - spec/rubocop/formatter/junit_formatter_spec.rb
#
#RSpec/PredicateMatcher:
#  EnforcedStyle: explicit
#
#RSpec/MessageSpies:
#  EnforcedStyle: receive
#
#RSpec/NestedGroups:
#  Max: 7
#
#RSpec/MultipleMemoizedHelpers:
#  Enabled: false
#
#RSpec/StubbedMock:
#  Enabled: false

Performance/CollectionLiteralInLoop:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'

Performance/EndWith:
  SafeMultiline: false

Performance/StartWith:
  SafeMultiline: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: true

Style/BlockDelimiters:
  AllowedMethods:
    - 'debug'

Style/ClassAndModuleChildren:
  Enabled: false

Style/FetchEnvVar:
  Exclude:
    - 'config/routes.rb'

Style/OpenStructUse:
  Exclude:
    - 'test/lib/*.rb'

Style/OptionalBooleanParameter:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RequireOrder:
  Enabled: false
