# Cron expression generator:
# https://crontab.cronhub.io/

Create new dungeons:
  cron: "0/2 * * * *"
  class: "DungeonCreateWorker"
  queue: environment-normal
  timezone: "UTC"

Schedule dungeon expirations:
  cron: "1/2 * * * *"
  class: "DungeonExpirationScheduler"
  queue: environment-normal
  timezone: "UTC"

Destroy expired dungeons:
  cron: "0 * * * *"
  class: "DungeonDestroyWorker"
  queue: slow
  timezone: "UTC"

Schedule events:
  cron: "0 0 * * *"
  class: "EventsScheduler"
  queue: environment-normal
  timezone: "UTC"
